version: "2"
services:
  hello-world-service:
    image: 905418067656.dkr.ecr.us-west-2.amazonaws.com/hello-world:latest
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-group: "/ecs/hello-world"
        awslogs-region: "us-west-2"
        awslogs-stream-prefix: "ecs"
    network_mode: awsvpc
    deploy:
      task_definition: /root/hello-world-nodejs-ecs/task-definition.json
