version: "2"
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: ecsTaskExecutionRole
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 512
  services:
    hello-world:
      image: 905418067656.dkr.ecr.us-west-2.amazonaws.com/hello-world:latest
      ports:
        - "3000: 3000"
      logging:
        driver: awslogs
        options:
          awslogs-group: "/ecs/hello-world"
          awslogs-region: "us-west-2"
          awslogs-stream-prefix: "ecs"
